// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYwED-DpDCN8qVug2WIliNF3SQGJf6K-0',
    appId: '1:463681512116:web:d827380f0804a51ba72de1',
    messagingSenderId: '463681512116',
    projectId: 'houzi-de24a',
    authDomain: 'houzi-de24a.firebaseapp.com',
    storageBucket: 'houzi-de24a.firebasestorage.app',
    measurementId: 'G-WBFGWB9T3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNQTERPToFnzKoOHyjulgxL4EQ-ClNm8',
    appId: '1:463681512116:android:498629e4065e5103a72de1',
    messagingSenderId: '463681512116',
    projectId: 'houzi-de24a',
    storageBucket: 'houzi-de24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjY0cz6C8ywazeNHZKO3caylNdtHPNdIM',
    appId: '1:463681512116:ios:5d0c53360cef5030a72de1',
    messagingSenderId: '463681512116',
    projectId: 'houzi-de24a',
    storageBucket: 'houzi-de24a.firebasestorage.app',
    iosBundleId: 'com.houzi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjY0cz6C8ywazeNHZKO3caylNdtHPNdIM',
    appId: '1:463681512116:ios:be296c7ca375d761a72de1',
    messagingSenderId: '463681512116',
    projectId: 'houzi-de24a',
    storageBucket: 'houzi-de24a.firebasestorage.app',
    iosBundleId: 'com.houzi.houzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYwED-DpDCN8qVug2WIliNF3SQGJf6K-0',
    appId: '1:463681512116:web:32f9e08d33098eaba72de1',
    messagingSenderId: '463681512116',
    projectId: 'houzi-de24a',
    authDomain: 'houzi-de24a.firebaseapp.com',
    storageBucket: 'houzi-de24a.firebasestorage.app',
    measurementId: 'G-4HNTZWB3YF',
  );
}
